# Generated by Django 5.1.1 on 2024-09-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
        migrations.AlterModelTable(name="customuser", table="USERS",),
    ]
