# Generated by Django 5.1.1 on 2024-09-26 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0002_alter_budget_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
