# Generated by Django 5.1.1 on 2024-10-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0007_alter_budgetentry_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetentry",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgeting.category"
            ),
        ),
    ]
