# Generated by Django 5.1.1 on 2024-10-05 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0006_category_alter_budgetentry_category"),
        ("expense_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgeting.category"
            ),
        ),
    ]
